name: Pass TEST_SECRET to page

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false #needed for unknown reason see https://github.com/marketplace/actions/deploy-to-github-pages
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.JEKYLL_PAT }}
          BRANCH: gh-pages
          FOLDER: dist